version: '3.1'

services:

  db:
    image: postgres
    restart: always
    container_name: database
    environment:
      POSTGRES_PASSWORD: gorm
      POSTGRES_USER: gorm
      POSTGRES_DB: gorm
    ports:
      - 5432:5432
  api:
    image: choaching-api
    restart: always
    container_name: my-api
    environment:
      CHOACHING_API_PORT: 8080
    ports:
      - 8080:8080
  cache:
    image: redis
    restart: always
    container_name: cache
    ports:
      - 6379:6379